"""mod_table

Revision ID: 66386d276b63
Revises: 8ebdcde24d40
Create Date: 2023-08-02 22:17:05.335087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66386d276b63'
down_revision = '8ebdcde24d40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.alter_column('invested_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('fully_invested',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('create_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.alter_column('invested_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('fully_invested',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('create_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.alter_column('create_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('fully_invested',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('invested_amount',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.alter_column('create_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('fully_invested',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('invested_amount',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
